### ISSUE TITLE
contenu des boutons qui se duplique

### ISSUE THREAD

**Issue by JaRoD41** [IVOOCodeHub/usv_migration_utilities#3]
lors de l'ajout de plusieurs boutons (ou autre composants parfois) dans la page, le contenu que l'on entre, lors de l'étape d'annotation, se duplique de façon aléatoire sur d'autres éléments du même type. Il est alors obligatoire de passer en base de données et de corriger manuellement les infos.

**Comment by Nilyss** [comment]
@JaRoD41 
Une MaJ en prod vient d'être déployer pour corriger ce bug. J'attends un retour de confirmation car je n'ai pas l'occasion de testé rapidement si le correctif fonctionne, avant de clôturer l'issues.

**Comment by Nilyss** [comment]
Exemple de l'ajout de spécificité sur la désignation d'un composant.

<img width="822" alt="Screenshot 2024-10-11 at 11 13 57" src="https://github.com/user-attachments/assets/e0a83eac-5795-477c-b19d-41fb719388ea">
<img width="758" alt="Screenshot 2024-10-11 at 11 14 40" src="https://github.com/user-attachments/assets/16f8ceca-7fd9-4688-9e87-1a8ef38833e5">
